### ISSUE TITLE
Services missing and position needs to be centered in the frame

### ISSUE THREAD

**Issue by samisfierce** [Cryingcactus/tgthr#10]
![image](https://user-images.githubusercontent.com/24820904/112383496-69a9d980-8caa-11eb-84e2-a27f9449c0f4.png)

**Comment by Cryingcactus** [comment]
I dont actually know what you mean. If you mean the copy should be a bit higher I can do that but the keywords section on the right is a cms thing, I just didnt want to add them all when I was building the page tbh

**Comment by Cryingcactus** [comment]
I am going to close this issue. Let me know if it still needs something
