### ISSUE TITLE
Who we help goes onto  two lines and should stay on one

### ISSUE THREAD

**Issue by samisfierce** [Cryingcactus/tgthr#32]
Can we have these  stay on one line and just get smaller until it reaches a mobile size?

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/24820904/116258047-971ef280-a742-11eb-955e-14af4f9e9120.png">

**Comment by Cryingcactus** [comment]
looks like your browser isnt full screen. This is caused from the right/left margins. If the window is full sized it should be 1 row. If there isnt enough room it will wrap the extras to another row. 

Is this how you would expect the behavior to be?

**Comment by samisfierce** [comment]
Ideally it  would stay at 4/row and maybe just get a little smaller or reduce spacing? I don't like one by itself... so if we have to cut to multiple rows I think either 4/2+2/1+1+1+1 is best
