### ISSUE TITLE
Contact page on mobile - just remove the let's get together text

### ISSUE THREAD

**Issue by samisfierce** [Cryingcactus/tgthr#49]
Remove the "let's get tgthr" text on mobile and just do the form
Hide the footer for this section.

https://user-images.githubusercontent.com/24820904/116749501-090b6c00-a9cf-11eb-83b9-5b9d9803e418.mov

**Comment by samisfierce** [comment]
Looks like this didn't update on mobile. 


https://user-images.githubusercontent.com/24820904/117000453-b7046800-aca6-11eb-9df9-c2d894eebcd1.mov

**Comment by Cryingcactus** [comment]
Worked for some screen sizes, now works for all mobile sizes
