### ISSUE TITLE
Hide sam photo on mobile

### ISSUE THREAD

**Issue by samisfierce** [Cryingcactus/tgthr#50]
As much as I love a giant photo of myself let's hide this on mobile hahahah

![IMG_1971](https://user-images.githubusercontent.com/24820904/116749585-2809fe00-a9cf-11eb-80d0-349c62880f4e.PNG)

**Comment by samisfierce** [comment]
Still peeking out a bit lol

![Uploading IMG_2113.PNG…]()

**Comment by Cryingcactus** [comment]
Now works for all screen sizes
